// Code generated by protoc-gen-go. DO NOT EDIT.
// source: ykgame.proto

/*
Package YKGameMsg is a generated protocol buffer package.

It is generated from these files:
	ykgame.proto

It has these top-level messages:
	LoginMsgReq
	LoginMsgRsp
	HeartBeatMsg
	ReadyGame
	StPlayer
	GameBegin
	GameEnd
	PlayMsg
	PlayErrMsg
*/
package YKGameMsg

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type LoginMsgReq struct {
	Uid       uint32 `protobuf:"varint,1,opt,name=uid" json:"uid,omitempty"`
	Pwd       string `protobuf:"bytes,2,opt,name=Pwd" json:"Pwd,omitempty"`
	CheckCode string `protobuf:"bytes,3,opt,name=CheckCode" json:"CheckCode,omitempty"`
	Ret       uint32 `protobuf:"varint,4,opt,name=Ret" json:"Ret,omitempty"`
}

func (m *LoginMsgReq) Reset()                    { *m = LoginMsgReq{} }
func (m *LoginMsgReq) String() string            { return proto.CompactTextString(m) }
func (*LoginMsgReq) ProtoMessage()               {}
func (*LoginMsgReq) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *LoginMsgReq) GetUid() uint32 {
	if m != nil {
		return m.Uid
	}
	return 0
}

func (m *LoginMsgReq) GetPwd() string {
	if m != nil {
		return m.Pwd
	}
	return ""
}

func (m *LoginMsgReq) GetCheckCode() string {
	if m != nil {
		return m.CheckCode
	}
	return ""
}

func (m *LoginMsgReq) GetRet() uint32 {
	if m != nil {
		return m.Ret
	}
	return 0
}

type LoginMsgRsp struct {
	Ret      uint32 `protobuf:"varint,1,opt,name=Ret" json:"Ret,omitempty"`
	NickName string `protobuf:"bytes,2,opt,name=NickName" json:"NickName,omitempty"`
}

func (m *LoginMsgRsp) Reset()                    { *m = LoginMsgRsp{} }
func (m *LoginMsgRsp) String() string            { return proto.CompactTextString(m) }
func (*LoginMsgRsp) ProtoMessage()               {}
func (*LoginMsgRsp) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *LoginMsgRsp) GetRet() uint32 {
	if m != nil {
		return m.Ret
	}
	return 0
}

func (m *LoginMsgRsp) GetNickName() string {
	if m != nil {
		return m.NickName
	}
	return ""
}

type HeartBeatMsg struct {
	HeartBeat bool `protobuf:"varint,1,opt,name=HeartBeat" json:"HeartBeat,omitempty"`
}

func (m *HeartBeatMsg) Reset()                    { *m = HeartBeatMsg{} }
func (m *HeartBeatMsg) String() string            { return proto.CompactTextString(m) }
func (*HeartBeatMsg) ProtoMessage()               {}
func (*HeartBeatMsg) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

func (m *HeartBeatMsg) GetHeartBeat() bool {
	if m != nil {
		return m.HeartBeat
	}
	return false
}

type ReadyGame struct {
	Ready bool `protobuf:"varint,1,opt,name=Ready" json:"Ready,omitempty"`
}

func (m *ReadyGame) Reset()                    { *m = ReadyGame{} }
func (m *ReadyGame) String() string            { return proto.CompactTextString(m) }
func (*ReadyGame) ProtoMessage()               {}
func (*ReadyGame) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{3} }

func (m *ReadyGame) GetReady() bool {
	if m != nil {
		return m.Ready
	}
	return false
}

type StPlayer struct {
	Seat  int32   `protobuf:"varint,1,opt,name=Seat" json:"Seat,omitempty"`
	Cards []int32 `protobuf:"varint,2,rep,packed,name=cards" json:"cards,omitempty"`
}

func (m *StPlayer) Reset()                    { *m = StPlayer{} }
func (m *StPlayer) String() string            { return proto.CompactTextString(m) }
func (*StPlayer) ProtoMessage()               {}
func (*StPlayer) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{4} }

func (m *StPlayer) GetSeat() int32 {
	if m != nil {
		return m.Seat
	}
	return 0
}

func (m *StPlayer) GetCards() []int32 {
	if m != nil {
		return m.Cards
	}
	return nil
}

type GameBegin struct {
	Seat    int32       `protobuf:"varint,1,opt,name=Seat" json:"Seat,omitempty"`
	Players []*StPlayer `protobuf:"bytes,2,rep,name=players" json:"players,omitempty"`
}

func (m *GameBegin) Reset()                    { *m = GameBegin{} }
func (m *GameBegin) String() string            { return proto.CompactTextString(m) }
func (*GameBegin) ProtoMessage()               {}
func (*GameBegin) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{5} }

func (m *GameBegin) GetSeat() int32 {
	if m != nil {
		return m.Seat
	}
	return 0
}

func (m *GameBegin) GetPlayers() []*StPlayer {
	if m != nil {
		return m.Players
	}
	return nil
}

type GameEnd struct {
	Winner  int32       `protobuf:"varint,1,opt,name=Winner" json:"Winner,omitempty"`
	Players []*StPlayer `protobuf:"bytes,2,rep,name=players" json:"players,omitempty"`
}

func (m *GameEnd) Reset()                    { *m = GameEnd{} }
func (m *GameEnd) String() string            { return proto.CompactTextString(m) }
func (*GameEnd) ProtoMessage()               {}
func (*GameEnd) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{6} }

func (m *GameEnd) GetWinner() int32 {
	if m != nil {
		return m.Winner
	}
	return 0
}

func (m *GameEnd) GetPlayers() []*StPlayer {
	if m != nil {
		return m.Players
	}
	return nil
}

type PlayMsg struct {
	Players  *StPlayer `protobuf:"bytes,1,opt,name=Players" json:"Players,omitempty"`
	NextSeat int32     `protobuf:"varint,2,opt,name=NextSeat" json:"NextSeat,omitempty"`
	Ret      uint32    `protobuf:"varint,3,opt,name=Ret" json:"Ret,omitempty"`
}

func (m *PlayMsg) Reset()                    { *m = PlayMsg{} }
func (m *PlayMsg) String() string            { return proto.CompactTextString(m) }
func (*PlayMsg) ProtoMessage()               {}
func (*PlayMsg) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{7} }

func (m *PlayMsg) GetPlayers() *StPlayer {
	if m != nil {
		return m.Players
	}
	return nil
}

func (m *PlayMsg) GetNextSeat() int32 {
	if m != nil {
		return m.NextSeat
	}
	return 0
}

func (m *PlayMsg) GetRet() uint32 {
	if m != nil {
		return m.Ret
	}
	return 0
}

type PlayErrMsg struct {
	Players *StPlayer `protobuf:"bytes,1,opt,name=Players" json:"Players,omitempty"`
	ErrCode int32     `protobuf:"varint,2,opt,name=ErrCode" json:"ErrCode,omitempty"`
}

func (m *PlayErrMsg) Reset()                    { *m = PlayErrMsg{} }
func (m *PlayErrMsg) String() string            { return proto.CompactTextString(m) }
func (*PlayErrMsg) ProtoMessage()               {}
func (*PlayErrMsg) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{8} }

func (m *PlayErrMsg) GetPlayers() *StPlayer {
	if m != nil {
		return m.Players
	}
	return nil
}

func (m *PlayErrMsg) GetErrCode() int32 {
	if m != nil {
		return m.ErrCode
	}
	return 0
}

func init() {
	proto.RegisterType((*LoginMsgReq)(nil), "YKGameMsg.LoginMsgReq")
	proto.RegisterType((*LoginMsgRsp)(nil), "YKGameMsg.LoginMsgRsp")
	proto.RegisterType((*HeartBeatMsg)(nil), "YKGameMsg.HeartBeatMsg")
	proto.RegisterType((*ReadyGame)(nil), "YKGameMsg.ReadyGame")
	proto.RegisterType((*StPlayer)(nil), "YKGameMsg.StPlayer")
	proto.RegisterType((*GameBegin)(nil), "YKGameMsg.GameBegin")
	proto.RegisterType((*GameEnd)(nil), "YKGameMsg.gameEnd")
	proto.RegisterType((*PlayMsg)(nil), "YKGameMsg.playMsg")
	proto.RegisterType((*PlayErrMsg)(nil), "YKGameMsg.playErrMsg")
}

func init() { proto.RegisterFile("ykgame.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 339 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x9c, 0x52, 0x4d, 0x4f, 0xc2, 0x40,
	0x10, 0x4d, 0x29, 0x50, 0x3a, 0x60, 0x62, 0x56, 0x63, 0x1a, 0xe3, 0x01, 0xf7, 0xc4, 0x41, 0x38,
	0xa8, 0x37, 0x6f, 0x10, 0xa2, 0x89, 0x42, 0x9a, 0x25, 0xc6, 0x78, 0x5c, 0xe9, 0x58, 0x1b, 0xa4,
	0xc5, 0xed, 0x1a, 0xe5, 0xdf, 0x9b, 0xd9, 0xee, 0x16, 0x0f, 0x7a, 0xd0, 0xdb, 0xbc, 0xc9, 0xfb,
	0xd8, 0x9d, 0x19, 0xe8, 0x6d, 0x57, 0xa9, 0x5c, 0xe3, 0x68, 0xa3, 0x0a, 0x5d, 0xb0, 0xf0, 0xf1,
	0xf6, 0x5a, 0xae, 0x71, 0x56, 0xa6, 0x5c, 0x42, 0xf7, 0xae, 0x48, 0xb3, 0x7c, 0x56, 0xa6, 0x02,
	0xdf, 0xd8, 0x3e, 0xf8, 0xef, 0x59, 0x12, 0x79, 0x7d, 0x6f, 0xb0, 0x27, 0xa8, 0xa4, 0x4e, 0xfc,
	0x91, 0x44, 0x8d, 0xbe, 0x37, 0x08, 0x05, 0x95, 0xec, 0x04, 0xc2, 0xc9, 0x0b, 0x2e, 0x57, 0x93,
	0x22, 0xc1, 0xc8, 0x37, 0xfd, 0x5d, 0x83, 0xf8, 0x02, 0x75, 0xd4, 0xac, 0x1c, 0x04, 0x6a, 0x7e,
	0xf5, 0x2d, 0xa2, 0xdc, 0x38, 0x82, 0x57, 0x13, 0xd8, 0x31, 0x74, 0xe6, 0xd9, 0x72, 0x35, 0x97,
	0x6b, 0xb4, 0x39, 0x35, 0xe6, 0x67, 0xd0, 0xbb, 0x41, 0xa9, 0xf4, 0x18, 0xa5, 0x9e, 0x95, 0x29,
	0x85, 0xd7, 0xd8, 0x78, 0x74, 0xc4, 0xae, 0xc1, 0x4f, 0x21, 0x14, 0x28, 0x93, 0x2d, 0xfd, 0x8e,
	0x1d, 0x42, 0xcb, 0x00, 0x4b, 0xab, 0x00, 0xbf, 0x84, 0xce, 0x42, 0xc7, 0xaf, 0x72, 0x8b, 0x8a,
	0x31, 0x68, 0x2e, 0x9c, 0x4f, 0x4b, 0x98, 0x9a, 0x54, 0x4b, 0xa9, 0x92, 0x32, 0x6a, 0xf4, 0xfd,
	0x41, 0x4b, 0x54, 0x80, 0xcf, 0x21, 0x24, 0xcf, 0x31, 0xa6, 0x59, 0xfe, 0xa3, 0x6c, 0x08, 0xc1,
	0xc6, 0x98, 0x56, 0xc2, 0xee, 0xf9, 0xc1, 0xa8, 0x1e, 0xf2, 0xc8, 0x05, 0x0a, 0xc7, 0xe1, 0x31,
	0x04, 0xb4, 0x8f, 0x69, 0x9e, 0xb0, 0x23, 0x68, 0x3f, 0x64, 0x79, 0x8e, 0xca, 0xfa, 0x59, 0xf4,
	0x57, 0xc7, 0xe7, 0x8a, 0x4e, 0x33, 0x1a, 0x42, 0x10, 0x5b, 0x25, 0x59, 0xfe, 0xa6, 0xb4, 0x1c,
	0x33, 0x7e, 0xfc, 0xd4, 0xe6, 0x4b, 0x0d, 0xf3, 0x84, 0x1a, 0xbb, 0x65, 0xf9, 0xbb, 0x6d, 0xde,
	0x03, 0x50, 0xce, 0x54, 0xa9, 0x7f, 0x44, 0x45, 0x10, 0x4c, 0x95, 0x32, 0x87, 0x53, 0x25, 0x39,
	0xf8, 0xd4, 0x36, 0x97, 0x79, 0xf1, 0x15, 0x00, 0x00, 0xff, 0xff, 0x00, 0x88, 0xe5, 0x82, 0xa9,
	0x02, 0x00, 0x00,
}
